<!-- /**CREA UNA COPIA DE IRPF.PHP CONGET EN VEZ DE POST Y CONTROLAR LOS ERRORES DE ENVIAREL FORMULARIO VACIO

-CONTROLAR EN TODOS LOS DEMAS FORMULARIOS HECHOS CON POST QUE SI SE MANDAN LOS CAMPOS VACIOS, SE MUESTRE UN MENSAJE

DEFASE OBJETO-RELACIONAL

SELECT nombre,precio,categoria
        FROM productos
        LIMIT 50;

$producto = new Producto();

CRAWLERS**/ -->